language: cpp
os: linux
dist: bionic

install:
  # Qt
  - sudo apt-get --yes install build-essential
  - sudo apt-get --yes install qt5-default

  # Qt Charts
  - sudo apt-get --yes install libqt5charts5 libqt5charts5-dev

  # Qt WebEngine
  - sudo apt-get --yes install qtwebengine5-dev

# Compilation
script:
  - qmake && make -s -j`nproc`

notifications:
  recipients:
    - blasteralex@yandex.ru
  email:
    on_success: change
    on_failure: change